# MCU name
MCU = MKL26Z64  #cortex-m0plus
USE_CHIBIOS_CONTRIB = yes

BOOTLOADER = halfkay

EXTRAKEY_ENABLE 	= yes
NKRO_ENABLE 		= yes
CONSOLE_ENABLE		= yes
COMMAND_ENABLE		= yes
MOUSEKEY_ENABLE 	= yes

OPT_DEFS += -DCORTEX_ENABLE_WFI_IDLE=TRUE
